apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: lamp
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: mysqlx
      port: 33060
      targetPort: 33060
  selector:
    app: lamp
    tier: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: lamp
spec:
  ports:
    - name: http
      port: 8080             #port access inside the cluster network
      targetPort: 8080       #port match the containerPort in the Deployment
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: lamp
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-mysql-backend
  labels:
    app: lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lamp
        tier: mysql
    spec:
      containers:
        - image: lamp-mysql:lts-debian13
          imagePullPolicy: Never         # Forces K8s to only use the local image
          name: lamp-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-secret-pw"
          ports:
            - containerPort: 3306
              name: mysql
            - containerPort: 33060
              name: mysqlx
          volumeMounts:
            - name: mysql-data-dir
              mountPath: /var/lib/mysql
            - name: mysql-runtime-dir
              mountPath: /run/mysqld
            - name: mysql-cert-dir
              mountPath: /opt/mysql/certs
            - name: my-cnf-file
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
      volumes:
      - name: mysql-data-dir
        hostPath:
          path: /myvol/mysql_data
          type: Directory
      - name: mysql-runtime-dir
        hostPath:
          path: /myvol/mysql_run
          type: Directory
      - name: mysql-cert-dir
        hostPath:
          path: /myvol/certs/mysql
          type: Directory
      - name: my-cnf-file
        configMap:
          name: my-cnf

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-httpd-php-frontend
  labels:
    app: lamp
spec:
  selector:
    matchLabels:
      app: lamp
      tier: frontend
  template:
    metadata:
      labels:
        app: lamp
        tier: frontend
    spec:
      containers:
        - image: lamp-httpd:2.4.68-debian13
          imagePullPolicy: Never
          name: httpd
          ports:
            - containerPort: 80
              name: httpd
          volumeMounts:
            - name: document-root
              mountPath: /usr/local/apache2/htdocs  # The folder INSIDE your application container
            - name: httpd-cert-dir
              mountPath: /usr/local/apache2/conf/certs
            - name: httpd-log
              mountPath: /usr/local/apache2/logs
            - name: httpd-conf-file
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
            - name: httpd-ssl-conf-file
              mountPath: /usr/local/apache2/conf/httpd-ssl.conf
              subPath: httpd-ssl.conf
        - image: lamp-php:8.5.8-debian13-fpm
          imagePullPolicy: Never
          name: php-fpm
          volumeMounts:
            - name: document-root
              mountPath: /var/www/html
            - name: mysql-cert-dir
              mountPath: /opt/php/mysql_certs
            - name: php-ini-file
              mountPath: /opt/php/etc/php/php.ini
              subPath: php.ini

      volumes:
        - name: document-root
          hostPath:
            path: /myvol/htdocs
            type: Directory
        - name: httpd-cert-dir
          hostPath:
            path: /myvol/certs/httpd
            type: Directory
        - name: httpd-log
          hostPath:
            path: /myvol/log/httpd
            type: Directory
        - name: httpd-conf-file
          configMap:
            name: httpd-conf
        - name: httpd-ssl-conf-file
          configMap: 
            name: httpd-ssl-conf
        - name: mysql-cert-dir
          hostPath:
            path: /myvol/certs/mysql
            type: Directory
        - name: php-ini-file
          configMap:
            name: php-ini
